version: "3"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

  db:
    image: postgres:12.4
    
    environment:
        # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
