version: "3"

services:
  app:
    build: .
    ports:
      - "8081:8080"
    # env_file:
    #   - .env.dev
    depends_on:
      - db
    environment:
      - POSTGRES_USER=darix
      - POSTGRES_PASSWORD=darix
      - POSTGRES_DB=darix
      - POSTGRES_SERVER=db
      - PYTHONPATH=/app

  db:
    image: postgres:12.4
    
    environment:
        # if user, pass, and db changes, need to remove previous containers # docker-compose rm -vf
      - POSTGRES_USER=darix
      - POSTGRES_PASSWORD=darix
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U darix"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
